# Generated by Django 5.2.17 on 2026-09-09 21:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80, unique=True, verbose_name='nome')),
                ('slug', models.SlugField(blank=True, help_text='Preenchido automaticamente a partir do nome.', max_length=80, unique=True, verbose_name='endereço curto')),
                ('ativo', models.BooleanField(default=True, help_text='Desmarque para esconder a área sem apagar os eventos dela.', verbose_name='ativo')),
                ('gestores', models.ManyToManyField(blank=True, related_name='areas_geridas', to=settings.AUTH_USER_MODEL, verbose_name='quem pode administrar')),
            ],
            options={
                'verbose_name': 'curso/área',
                'verbose_name_plural': 'cursos/áreas',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=160, verbose_name='título')),
                ('descricao', models.TextField(blank=True, help_text='Uma ou duas frases sobre a atividade.', verbose_name='descrição')),
                ('data', models.DateField(verbose_name='data')),
                ('hora_inicio', models.TimeField(verbose_name='horário de início')),
                ('hora_fim', models.TimeField(blank=True, null=True, verbose_name='horário de término')),
                ('local', models.CharField(blank=True, max_length=120, verbose_name='local')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='cadastrado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='última alteração')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='eventos', to='eventos.area', verbose_name='curso/área')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_criados', to=settings.AUTH_USER_MODEL, verbose_name='cadastrado por')),
            ],
            options={
                'verbose_name': 'evento',
                'verbose_name_plural': 'eventos',
                'ordering': ['data', 'hora_inicio', 'titulo'],
                'indexes': [models.Index(fields=['data', 'hora_inicio'], name='eventos_eve_data_45ab24_idx')],
            },
        ),
    ]
