# Generated by Django 5.2.17 on 2026-09-09 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0002_areas_iniciais'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='inscricoes_abertas',
            field=models.BooleanField(default=False, help_text='Desmarcado, a página mostra “Inscrições em breve”.', verbose_name='inscrições abertas'),
        ),
        migrations.AddField(
            model_name='area',
            name='link_inscricao',
            field=models.URLField(blank=True, help_text='Endereço da inscrição no SUAP. Sem ele não aparece botão, mesmo com as inscrições marcadas como abertas.', max_length=300, verbose_name='link de inscrição'),
        ),
    ]
